version: '3.8'

services:
    api1:
        hostname: api1
        depends_on:
            - db
        build: .
        ports:
            - 8080
    api2:
        hostname: api2
        depends_on:
            - db
        build: .
        ports:
            - 8080
    proxy:
        image: nginx:alpine
        ports:
            - 9999:80
        volumes:
            # mount the nginx configuration
            - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2
    db:
        hostname: db
        image: postgres:16-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            # -  ./build/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    db-data:
