version: '3.8'

services:
    api1:
        hostname: api1
        build: .
        ports:
            - 8081:8080
    api2:
        hostname: api2
        build: .
        ports:
            - 8082:8080
    proxy:
        image: nginx:alpine
        ports:
            - 9999:80
        volumes:
            - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api1
            - api2
